### ISSUE TITLE
Selling to guide and then killing him causes negative gold drop

### ISSUE THREAD

**Issue by The-Host** [Progether/JAdventure#222]
Depending on how much the items you sold to the guide were worth, a negative sum equal to that of the total gold cost of the items will be dropped by the guide on death. This effectively brings you back to zero if you started out with no gold before selling to him.

**Comment by projectdelphai** [comment]
This bug may also exist for other npcs (since they eventually should be able to sell/buy with players).

**Comment by The-Host** [comment]
My best guess is that he has his on hand gold reduced into the negatives by buying your items. Since he starts at zero, it just dips below zero as long as you sell to him. You just happen to be able to pick up his negative balance as a drop. I'm checking to see if buying from him adds to his gold drop at all.

**Comment by The-Host** [comment]
Lo and behold, buying items off of him increases his gold drop. Since I can't find a gold value in the npc json or in any other accompanying jsons (if there is, please direct me), I imagine he just happens to have a default gold drop of zero. There does happen to be a xp value in the npc json, would there be any trouble with adding a gold value in the json and have a test to decline a player a trade if the value goes below zero?

**Comment by projectdelphai** [comment]
That would actually be a great idea. It would force the player to think about whether it's really important to sell this item over that one. It would create an interesting dynamic. If implemented:

 1. the npc should start out with a gold value higher than 0 (maybe 100 or something?)
 1. and the npc should display the amount of gold he has so that that player can calculate the pros and cons of selling/buying certain items instead of having to guess.

**Comment by paddatrapper** [comment]
NPC's gold is now displayed while trading. NPCs start with a set amount of gold (100) as specified in [npcs.json](json/npcs.json). NPCs cannot buy items that would leave them with less than 0 gold.
